<!DOCTYPE html>
<html>
<head>
    <title>Amazon Search App</title>
    <link rel="stylesheet" type="text/css" href="public/css/body.css"/>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/body.js"></script>
</head>
<body>
<div class="cont">
    <div class="cont-cell">
        <?= $this->tag->form(array("", "class" => "request-form", "method" => "get")); ?>
        <?= $this->tag->textField("q"); ?>
        <?= $this->tag->submitButton("Search"); ?>
        </form>
        <div class="amazon-result"></div>
        <div id="floatingBarsG">
            <div class="blockG" id="rotateG_01">
            </div>
            <div class="blockG" id="rotateG_02">
            </div>
            <div class="blockG" id="rotateG_03">
            </div>
            <div class="blockG" id="rotateG_04">
            </div>
            <div class="blockG" id="rotateG_05">
            </div>
            <div class="blockG" id="rotateG_06">
            </div>
            <div class="blockG" id="rotateG_07">
            </div>
            <div class="blockG" id="rotateG_08">
            </div>
        </div>
    </div>
</div>
</body>
</html>