<!DOCTYPE html>
<html>
<head>
    <title>Amazon Search App</title>
    <link rel="stylesheet" type="text/css" href="public/css/body.css"/>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/body.js"></script>
</head>
<body>
<div class="cont">
    <div class="cont-cell">
        <?= $this->tag->form(array("", "class" => "request-form", "method" => "get")); ?>
        <?= $this->tag->textField("q"); ?>
        <?= $this->tag->submitButton("Search"); ?>
        </form>
        <div class="amazon-result"></div>
    </div>
</div>
</body>
</html>